import type { CornerTypeRow } from './corner-type-manager';

// Prisma cornerType 레코드 → CornerTypeRow (목록·그룹 상세 공용). updatedBy는 최근 감사 로그 변경자.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function toCornerTypeRow(r: any, updatedBy: string | null): CornerTypeRow {
  return {
    id: r.id,
    typeId: r.typeId,
    name: r.name,
    baseCategory: r.baseCategory,
    componentType: r.componentType ?? null,
    typeDetail: r.typeDetail,
    bigBanner: r.bigBanner ?? false,
    markupId: r.markupId,
    layout: r.layout,
    description: r.description,
    channels: r.channels,
    platforms: r.platforms,
    active: r.active,
    useMainTitle: r.useMainTitle,
    useSubTitle: r.useSubTitle,
    useMinItems: r.useMinItems,
    useMaxItems: r.useMaxItems,
    useNoDisplay: r.useNoDisplay,
    useMoreButton: r.useMoreButton,
    useBadge: r.useBadge ?? false,
    useImage: r.useImage ?? true,
    usePrice: r.usePrice ?? true,
    useDesc: r.useDesc ?? true,
    defaultMinItems: r.defaultMinItems ?? null,
    defaultMaxItems: r.defaultMaxItems ?? null,
    defaultSortStrategy: r.defaultSortStrategy ?? null,
    defaultRecSource: r.defaultRecSource ?? null,
    defaultMoreButton: r.defaultMoreButton ?? false,
    defaultMoreButtonLabel: r.defaultMoreButtonLabel ?? null,
    defaultMainTitle: r.defaultMainTitle ?? null,
    defaultSubTitle: r.defaultSubTitle ?? null,
    defaultSubTitleIcon: r.defaultSubTitleIcon ?? null,
    defaultCardShape: r.defaultCardShape ?? null,
    defaultBannerOptions: r.defaultBannerOptions ?? null,
    cvmFields: r.cvmFields ?? '',
    composition: r.composition ?? null,
    userCustomizable: r.userCustomizable ?? false,
    userMinItems: r.userMinItems ?? null,
    userMaxItems: r.userMaxItems ?? null,
    sampleImageUrl: r.sampleImageUrl,
    status: r.status,
    workingVersion: r.workingVersion ?? 1,
    liveVersion: r.liveVersion ?? null,
    liveAt: r.liveAt ? r.liveAt.toISOString() : null,
    createdBy: r.createdBy,
    updatedBy: updatedBy ?? r.createdBy ?? null,
    createdAt: r.createdAt.toISOString(),
    updatedAt: r.updatedAt.toISOString(),
  };
}
